#ifndef BLINKER_PROVISIONING_CONTROLLERCONTROLCOORDINATOR_H
#define BLINKER_PROVISIONING_CONTROLLERCONTROLCOORDINATOR_H

#include "ControllerGrantVerifier.h"
#include "../interface/IControllerCredentialStore.h"
#include "../interface/IOwnershipSource.h"

namespace blinker {

// Applies one server-authorized Ownership-domain controller mutation. It has
// no transport, BLE or HTTP dependency. It retains only the current device
// control nonce; exact mutation retries are delegated to the durable store.
class ControllerControlCoordinator {
public:
    ControllerControlCoordinator(
        const DeviceInstanceId& deviceInstanceId,
        IOwnershipSource& ownership,
        IControllerCredentialStore& credentials,
        ControllerGrantVerifier& verifier);
    ~ControllerControlCoordinator();
    ControllerControlCoordinator(
        const ControllerControlCoordinator&) = delete;
    ControllerControlCoordinator& operator=(
        const ControllerControlCoordinator&) = delete;

    // controlNonce must be freshly generated by the device-side control
    // session. Exact replay may reuse the same window; another nonce cannot
    // replace it until endControlWindow() (normally when the local control
    // transaction finishes or the session disconnects).
    Result beginControlWindow(ByteView controlNonce);
    void endControlWindow();
    bool controlWindowActive() const { return controlWindowActive_; }

    Result apply(
        ByteView encodedGrant,
        ByteView controllerSecret,
        uint64_t nowEpochSeconds,
        bool hasTrustedTime,
        MutableByteSpan operationWorkspace,
        MutableByteSpan output,
        ByteView& receipt);

private:
    DeviceInstanceId deviceInstanceId_;
    IOwnershipSource& ownership_;
    IControllerCredentialStore& credentials_;
    ControllerGrantVerifier& verifier_;
    uint8_t controlNonce_[kControllerControlNonceSize];
    bool controlWindowActive_;
};

} // namespace blinker

#endif
