#ifndef BLINKER_PROVISIONING_CONTROLLERCONTROLCOORDINATOR_H
#define BLINKER_PROVISIONING_CONTROLLERCONTROLCOORDINATOR_H

#include "ControllerGrantVerifier.h"
#include "../interface/IAccessEpochSource.h"
#include "../interface/IControllerCredentialStore.h"
#include "../interface/IDeviceAccessStore.h"
#include "PresenceKeyControlContract.h"

namespace blinker {

// Applies one server-authorized direct-access group mutation. It has
// no transport, BLE or HTTP dependency. It retains only the current device
// control nonce; exact mutation retries are delegated to the durable store.
class ControllerControlCoordinator {
public:
    ControllerControlCoordinator(
        const DeviceInstanceId& deviceInstanceId,
        IAccessEpochSource& accessEpoch,
        IControllerCredentialStore& credentials,
        ControllerGrantVerifier& verifier,
        IDeviceAccessStore* presenceAccess = nullptr);
    ~ControllerControlCoordinator();
    ControllerControlCoordinator(
        const ControllerControlCoordinator&) = delete;
    ControllerControlCoordinator& operator=(
        const ControllerControlCoordinator&) = delete;

    // controlNonce must be freshly generated by the device-side control
    // session. Exact replay may reuse the same window; another nonce cannot
    // replace it until endControlWindow() (normally when the local control
    // transaction finishes or the session disconnects).
    Result beginControlWindow(ByteView controlNonce);
    void endControlWindow();
    bool controlWindowActive() const { return controlWindowActive_; }
    ByteView controlNonce() const {
        return controlWindowActive_
                   ? ByteView(controlNonce_, sizeof(controlNonce_))
                   : ByteView();
    }

    Result apply(
        ByteView encodedGrant,
        ByteView controllerSecret,
        MutableByteSpan operationWorkspace,
        MutableByteSpan output,
        ByteView& receipt);
    Result applyPresence(
        ByteView encodedMutation,
        MutableByteSpan output,
        ByteView& receipt);
    bool supportsPresenceKeyControl() const {
        return presenceAccess_ != nullptr;
    }

private:
    const DeviceInstanceId& deviceInstanceId_;
    IAccessEpochSource& accessEpoch_;
    IControllerCredentialStore& credentials_;
    ControllerGrantVerifier& verifier_;
    IDeviceAccessStore* presenceAccess_;
    uint8_t controlNonce_[kControllerControlNonceSize];
    bool controlWindowActive_;
};

} // namespace blinker

#endif
