name=Blinker
version=0.3.12
author=i3water
maintainer=i3wawter
sentence=Build a easy way for your IoT project.
paragraph=Blinker library for embedded hardware. Support Arduino, ESP32, Arduino UNO R4 WiFi, Raspberry Pi Pico W, WiFi, BLE, MQTT.
category=Communication
url=https://diandeng.tech/home
architectures=*
