#ifndef BLINKER_PLATFORM_DETECTOR_H
#define BLINKER_PLATFORM_DETECTOR_H

#if defined(ESP32)
    #define BLINKER_PLATFORM_ESP32
    #define BLINKER_NATIVE_WIFI
    #define BLINKER_WIFI_PLATFORM_NAME "ESP32"
    #define BLINKER_WIFI_HAS_MDNS
    #define BLINKER_WIFI_HAS_WEBSOCKETS
    #define BLINKER_WIFI_HAS_SOFTAP
    #define BLINKER_WIFI_HAS_SMARTCONFIG
    #define BLINKER_WIFI_HAS_MULTI
    #define BLINKER_WIFI_HAS_INSECURE_CLIENT
#elif defined(ARDUINO_UNOWIFIR4)
    #define BLINKER_PLATFORM_UNO_R4_WIFI
    #define BLINKER_NATIVE_WIFI
    #define BLINKER_WIFI_PLATFORM_NAME "Arduino UNO R4 WiFi"
#elif defined(ARDUINO_RASPBERRY_PI_PICO_W) || \
      defined(ARDUINO_RASPBERRY_PI_PICO_2W) || \
      (defined(ARDUINO_ARCH_RP2040) && defined(PICO_CYW43_SUPPORTED))
    #define BLINKER_PLATFORM_RP2040_WIFI
    #define BLINKER_NATIVE_WIFI
    #define BLINKER_WIFI_PLATFORM_NAME "Raspberry Pi Pico W"
    #define BLINKER_WIFI_HAS_SOFTAP
    #define BLINKER_WIFI_HAS_INSECURE_CLIENT
#endif

#endif
