#include <BlinkerV2/protocol/bbp2/Frame.inc>
#include <BlinkerV2/protocol/bbp2/KeyedBody.inc>
#include <BlinkerV2/protocol/bbp2/Messages.inc>
#include <BlinkerV2/protocol/DirectRecord.inc>
#include <BlinkerV2/protocol/ble/Fragment.inc>
#include <BlinkerV2/protocol/ble/Mode.inc>
#include <BlinkerV2/protocol/ble/Presence.inc>
#include <BlinkerV2/protocol/cbor/Cbor.inc>
#include <BlinkerV2/protocol/gateway/Contracts.inc>
#include <BlinkerV2/protocol/noise/LocalSecureRecord.inc>
