#ifndef BLINKER_V2_ADVANCED_H
#define BLINKER_V2_ADVANCED_H

// Engineering/adapter entry point. Application sketches should start with
// Blinker.h and move here only when they intentionally own protocol/runtime
// storage, control-plane services or low-level transport composition.

#include "BlinkerV2/api/BlinkerFacade.h"
#include "BlinkerV2/api/Client.h"
#include "BlinkerV2/api/EndpointHandle.h"
#include "BlinkerV2/api/Interactions.h"
#include "BlinkerV2/api/PatchBuilder.h"
#include "BlinkerV2/api/StateUpdate.h"
#include "BlinkerV2/core/Result.h"
#include "BlinkerV2/core/Crc32.h"
#include "BlinkerV2/core/Diagnostics.h"
#include "BlinkerV2/core/HmacSha256.h"
#include "BlinkerV2/core/HkdfSha256.h"
#include "BlinkerV2/core/SecureMemory.h"
#include "BlinkerV2/core/Sha256.h"
#include "BlinkerV2/core/Span.h"
#include "BlinkerV2/core/Utf8.h"
#include "BlinkerV2/control/DeviceKeySessionContract.h"
#include "BlinkerV2/control/HttpDeviceKeySessionProvider.h"
#include "BlinkerV2/control/Session.h"
#include "BlinkerV2/interface/IClock.h"
#include "BlinkerV2/interface/IDeviceKeySource.h"
#include "BlinkerV2/interface/IDeviceKeyStore.h"
#include "BlinkerV2/interface/IControllerCredentialSource.h"
#include "BlinkerV2/interface/IControllerCredentialStore.h"
#include "BlinkerV2/interface/IAccessEpochSource.h"
#include "BlinkerV2/interface/IDeviceAccessStore.h"
#include "BlinkerV2/interface/IAtomicBlobStore.h"
#include "BlinkerV2/interface/IHttpClient.h"
#include "BlinkerV2/interface/IAuthorizationProvider.h"
#include "BlinkerV2/interface/IBleLink.h"
#include "BlinkerV2/interface/IBleCentralPort.h"
#include "BlinkerV2/interface/IBleConnectionSecuritySource.h"
#include "BlinkerV2/interface/IBleModePreparation.h"
#include "BlinkerV2/interface/IBleModeLink.h"
#include "BlinkerV2/interface/ITransportLifecycle.h"
#include "BlinkerV2/interface/INoiseCryptoProvider.h"
#include "BlinkerV2/interface/IX25519AesGcmCryptoProvider.h"
#include "BlinkerV2/interface/IEd25519DigestVerifier.h"
#include "BlinkerV2/interface/IP256DigestVerifier.h"
#include "BlinkerV2/interface/IServerSignatureVerifier.h"
#include "BlinkerV2/interface/IMqttClient.h"
#include "BlinkerV2/interface/IRandom.h"
#include "BlinkerV2/interface/ILocalProvisioningApplication.h"
#include "BlinkerV2/interface/ISessionProvider.h"
#include "BlinkerV2/interface/IWifiCredentialSink.h"
#include "BlinkerV2/interface/IWifiStation.h"
#include "BlinkerV2/model/Endpoint.h"
#include "BlinkerV2/model/EndpointRegistry.h"
#include "BlinkerV2/model/EndpointStateStore.h"
#include "BlinkerV2/model/EndpointValue.h"
#include "BlinkerV2/model/Manifest.h"
#include "BlinkerV2/identity/DeviceInstanceId.h"
#include "BlinkerV2/identity/DeviceInstanceIdStore.h"
#include "BlinkerV2/identity/ConfiguredDeviceKeySource.h"
#include "BlinkerV2/identity/DeviceKey.h"
#include "BlinkerV2/identity/DeviceKeyStore.h"
#include "BlinkerV2/identity/DeviceAccessStore.h"
#include "BlinkerV2/identity/GatewayAccessStore.h"
#include "BlinkerV2/identity/ControllerCredential.h"
#include "BlinkerV2/provisioning/WifiCredential.h"
#include "BlinkerV2/provisioning/WifiCredentialStore.h"
#include "BlinkerV2/provisioning/DeviceKeyProvisioningEndpoint.h"
#include "BlinkerV2/provisioning/BleEnrollmentApplication.h"
#include "BlinkerV2/provisioning/BleEnrollmentContract.h"
#include "BlinkerV2/provisioning/BleEnrollmentGrant.h"
#include "BlinkerV2/provisioning/ControllerControlContract.h"
#include "BlinkerV2/provisioning/ControllerGrantVerifier.h"
#include "BlinkerV2/provisioning/ControllerControlCoordinator.h"
#include "BlinkerV2/provisioning/ControllerControlEndpoint.h"
#include "BlinkerV2/provisioning/PresenceKeyControlContract.h"
#include "BlinkerV2/protocol/bbp2/Frame.h"
#include "BlinkerV2/protocol/bbp2/KeyedBody.h"
#include "BlinkerV2/protocol/bbp2/Messages.h"
#include "BlinkerV2/protocol/cbor/Cbor.h"
#include "BlinkerV2/protocol/gateway/Contracts.h"
#include "BlinkerV2/protocol/ble/Fragment.h"
#include "BlinkerV2/protocol/ble/Gatt.h"
#include "BlinkerV2/protocol/ble/Mode.h"
#include "BlinkerV2/protocol/noise/LocalSecureRecord.h"
#include "BlinkerV2/protocol/noise/NoiseSuite.h"
#include "BlinkerV2/protocol/SetupSession.h"
#include "BlinkerV2/runtime/DeviceRuntime.h"
#include "BlinkerV2/runtime/ChildSessionCoordinator.h"
#include "BlinkerV2/runtime/GatewayAccessDeliveryProcessor.h"
#include "BlinkerV2/runtime/GatewayManagementClient.h"
#include "BlinkerV2/runtime/GatewayPresenceMatcher.h"
#include "BlinkerV2/runtime/GatewayChildSession.h"
#include "BlinkerV2/runtime/GatewayGattChildSession.h"
#include "BlinkerV2/runtime/DeviceKeySessionArena.h"
#include "BlinkerV2/runtime/BleOnlyLifecycle.h"
#include "BlinkerV2/runtime/BleSetupCompletion.h"
#include "BlinkerV2/runtime/BleSetupLifecycle.h"
#include "BlinkerV2/runtime/ReliableOutbox.h"
#include "BlinkerV2/runtime/WifiConnectionLifecycle.h"
#include "BlinkerV2/runtime/WifiCloudLifecycle.h"
#include "BlinkerV2/security/P256ServerKeyRingVerifier.h"
#include "BlinkerV2/security/P256Signature.h"
#include "BlinkerV2/security/Ed25519ServerKeyRingVerifier.h"
#include "BlinkerV2/security/Ed25519Signature.h"
#include "BlinkerV2/security/GatewayAccessEnvelopeSecurity.h"
#include "BlinkerV2/security/NoiseNn.h"
#include "BlinkerV2/security/ControllerHmacSha256Authorizer.h"
#include "BlinkerV2/security/ControllerHmacSha256Initiator.h"
#include "BlinkerV2/transport/IFrameTransport.h"
#include "BlinkerV2/protocol/DirectRecord.h"
#include "BlinkerV2/transport/BleRecordTransport.h"
#include "BlinkerV2/transport/BleFrameTransport.h"
#include "BlinkerV2/transport/GattDirectChildLink.h"
#include "BlinkerV2/transport/BleModeCoordinator.h"
#include "BlinkerV2/transport/ManagedMqttTransport.h"
#include "BlinkerV2/transport/MqttFrameTransport.h"
#include "BlinkerV2/transport/TransportHub.h"

// Advanced model-only declaration. Ordinary sketches pass interactions to
// the global Blinker.begin() and never construct Device explicitly.
#define BLINKER_DEVICE(name, ...)                                             \
    static const auto name##Schema =                                         \
        ::blinker::makeDeviceSchema(__VA_ARGS__);                            \
    ::blinker::Device name(name##Schema)

#endif
